# 1.2. Does the study have an associated expression of concern or other relevant post-publication notice?

```{r}
#| include: false
if(file.exists("../_setup.R")){source("../_setup.R")}
```

This check should be repeated shortly before finishing the systematic review, to identify any relevant notices issued during the conduct of the review.

Reviewers should check whether the publication or publications describing the study have associated expressions of concern or other post publication notices. Expressions of concern and other post publication notices, such as notifications, publisher notes, editor notes, etc., are not used and published as consistently as retractions. Expressions of concern are generally used when there are concerns raised about a publication but the evidence is inconclusive or the issue unresolved. Other notifications may be used to flag a potential issue or provide status updates.

Because of this variability, the content and purpose of the notice should be carefully considered when making a judgement. Similarly to retractions, be aware that the content of expressions of concern or other notifications can also be limited and not representative of all the journal's concerns relating to the issue.
If the notice indicates that there is an ongoing investigation then it is recommended that reviewers revisit the journal website to check for any updates prior to finishing the systematic review.

Expressions of concern can be checked while looking at whether publications associated with the study have been retracted, by checking the journal website and [Retraction Watch database](http://retractiondatabase.org/).

In addition to post-publication amendments and notices issued by journals or publishers, post-publication comments and critiques posted by researchers in the form of letters to the editor or posts on PubPeer (for example) relating to trustworthiness should also be considered. It is recommended to look for correspondence relating to the trial publication by citation searching in Web of Science or Scopus relating to the journal of trial publication. Searches of PubMed and Medline are recommended. It is also recommended to look for comments on PubPeer. These are readily accessed by downloading the [PubPeer plugin](https://www.pubpeer.com/static/extensions), which will automatically flag a study with comments if you are examining it. The presence of critical correspondence or PubPeer comments should not automatically trigger concerns however, because some critiques of this nature may lack merit, or may not relate to trustworthiness of the study. We recommend that these comments should be carefully considered, as they might assist the reviewer in completing their assessment using the INSPECT-SR tool (for example, by directing attention to a problematic feature that can then be incorporated into the corresponding domain-level judgement).

Further guidance for searching for post-publication amendments, including expressions of concern, is included in the [Cochrane Handbook for Systematic Reviews of Interventions](https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current/chapter-04-technical-supplement-searching-and-selecting-studies) and its associated technical supplement. You may wish to consult with an Information Specialist if further assistance is needed.

The answer to this check should contribute to a domain-level judgement.

## Examples

::: {.callout-note title = "Example 1"}
While assessing a clinical trial of a probiotic supplement for gestational diabetes, a reviewer searches for the study on [https://retractiondatabase.org/](https://retractiondatabase.org/) by searching on the study DOI. The index study is included in the search results, indicating that it has an associated post-publication notice, labelled as "Concerns/ Issues About data". Navigating to the article on the journal website reveals an "Editor's Note" reporting that the article is being investigated due to integrity concerns. The reviewer answers "yes" for this check, and this response contributes to the domain-level judgement.
:::

::: {.callout-note title = "Example 2"}
While assessing a clinical trial of a weight-loss drug, the reviewer identifies a critical comment on PubPeer. On reviewing the comment, the reviewer learns that the criticism relates to the dose of drug used in the study. Because this is not relevant to the assessment of the study's trustworthiness, and because no other post-publication notices relating to the study were identified, the reviewer answers "no" for this check, and this response contributes to the domain-level judgement.
:::
