# 1.1. Does the study have an associated retraction?

```{r}
#| include: false
if(file.exists("../_setup.R")){source("../_setup.R")}
```

This check should be repeated shortly before finishing the systematic review, to identify any retractions issued during the conduct of the review.

Reviewers should check whether the publication or publications describing the study have been retracted. Retractions highlight that there is a significant issue with the publication, such that the journal no longer stands by the article; once retracted, an article should no longer be considered part of the published record. The Committee for Publication Ethics provides guidelines on the reasons for retraction, though be aware that the content of retraction notices can be limited and not representative of all the journal's concerns relating to the reasons for retraction.

In rare instances, an article might be removed or withdrawn, rather than retracted, meaning that the article itself should no longer be available. This may occur when there has been a breach of confidentiality, publication of libellous content, or copyright or Intellectual Property infringement (for example). Removed or withdrawn articles should be treated in the same manner as retracted articles when using INSPECT-SR.

If a study report is retracted, it should be marked as such on the journal website, but not removed, and there should be a separate published retraction notice, also with a unique Digital Object Identifier (DOI). It is important to note that these processes may not be carried out in a systematic fashion across all journals nor indexed well by bibliographic databases.

Checking for retractions should be performed by accessing the online version of the publication on the journal website, where online notices may be found which have not been indexed elsewhere, and by searching the [Retraction Watch database](http://retractiondatabase.org/), which is the largest and most reliable database of retractions. Be aware that there may be typographic errors in the Retraction Watch database, so DOI may be more useful for searching. Reviewers should confirm that they are searching the Retraction Watch database rather than the associated Retraction Watch blog (i.e. that they are not using the search function at https://retractionwatch.com/ — this does not perform a search of the Retraction Watch database and is not a suitable approach to conducting this check).

Further guidance for searching for post-publication amendments, including retractions, is included in the [Cochrane Handbook for Systematic Reviews of Interventions](https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current/chapter-04-technical-supplement-searching-and-selecting-studies) and its associated technical supplement. You may wish to consult with an Information Specialist if further assistance is needed.

An answer of "yes" for this check would typically warrant a judgement of "serious concerns" for this domain and overall for the index study (i.e., the reviewer would not need to continue with other INSPECT-SR checks), regardless of the reason for retraction and particularly if it was for the main results paper. If the main results paper associated with a study has been retracted, a judgement of "serious concerns" will typically be warranted, regardless of the reason for the retraction. An exception would be where a study has been retracted and subsequently replaced by a new version (e.g. to correct an error). The replacement can then be assessed using INSPECT-SR.

## Example

::: {.callout-note title = "Example 1"}
While assessing a clinical trial of a probiotic supplement for gestational diabetes, a systematic reviewer navigates to the journal website. The article has been replaced with a retraction notice, noting that an external statistical review had been performed on the basis of "significant concerns…about the integrity of the data" raised by a third party. The notice states "the main outcome of the external review was that the article's conclusions are unreliable". The reviewer answers "yes" for this check, and this is sufficient to assign a judgement of "serious concerns" for the domain and for the study.
:::